#! /bin/sh

sxhkd &
polybar wow &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           12

bspc config normal_border_color  "#adadad"
bspc config focused_border_color "#739200"

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true

# spawn new window on the right side
bspc config initial_polarity second_child

# focus the window on mouse over it
bspc config focus_follows_pointer true

# rules
bspc rule -a TelegramDesktop desktop=^3 state=floating
bspc rule -a Firefox desktop=^1 state=tiled
bspc rule -a Emacs state=tiled

# set background
feh --bg-fill /home/artyom/.config/bspwm/CellPath_lede_fullwidth-2880x1620.jpg
